[package]
name = "tetris-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
if_chain = "1.0.2"
rand = "0.8.5"
serde = { version = "1.0.174", features = ["derive"] }

[dependencies.bevy]
version = "0.11.0"
features = ["dynamic_linking"]
