[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_renet = "0.0.9"
bincode = "1.3.3"
if_chain = "1.0.2"
rand = "0.8.5"
serde = { version = "1.0.174", features = ["derive"] }

[dependencies.bevy]
version = "0.11.0"
features = ["dynamic_linking"]
