[package]
name = "tetris-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.19", features = ["ws"] }
tetris-schema = { version = "0.1.0", path = "../schema" }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
